#!/bin/sh

pid=$(ps aux | grep -P '\sfactorio\s' | grep -v grep | awk -e '{print $2}')
if [[ -z $pid ]]; then

		pid=$(ps aux | grep -P '\sexp\d$' | grep -v grep | awk -e '{print $2}')
		if [[ -z $pid ]]; then
				echo "Factorio isn't running!"
				exit
		fi
fi
	 
echo "$pid"
cat /proc/$pid/maps
