#include "lua_imports.hpp"
#include "Inject.hpp"
#include "factstub_logger.hpp"

#define SAFE_BIND(s) \
	try { \
		lua_imports::s = tracee->FindSymbolAddressByPattern(#s);	\
  } catch (std::exception e) { \
    Logger::warning(e.what()); \ 
  } 

/*
#define BIND(s) \
	lua_imports::s = tracee->FindSymbolAddressByPattern(#s)
*/
#define BIND(s) SAFE_BIND(s)

void bind_imports (Tracee* tracee)
{
	BIND(lua_arith)
		BIND(lua_atpanic)
		BIND(lua_callk)
		BIND(lua_checkstack)
		BIND(lua_close)
		BIND(lua_compare)
		BIND(lua_concat)
		BIND(lua_copy)
		BIND(lua_createtable)
		BIND(lua_dump)
		BIND(lua_error)
		BIND(lua_gc)
		BIND(lua_getallocf)
		BIND(lua_getctx)
		BIND(lua_getfield)
		BIND(lua_getglobal)
		BIND(lua_getmetatable)
		BIND(lua_gettable)
		BIND(lua_gettop)
		BIND(lua_getuservalue)
		BIND(lua_insert)
		BIND(lua_iscfunction)
		BIND(lua_isfunction)
		BIND(lua_isnumber)
		BIND(lua_isstring)
		BIND(lua_isuserdata)
		BIND(lua_len)
		BIND(lua_load)
		BIND(lua_newstate)
		BIND(lua_newthread)
		BIND(lua_newuserdata)
		BIND(lua_next)
		BIND(lua_pcallk)
		BIND(lua_pushboolean)
		BIND(lua_pushcclosure)
		BIND(lua_pushfstring)
		BIND(lua_pushinteger)
		BIND(lua_pushlightuserdata)
		BIND(lua_pushlstring)
		BIND(lua_pushnil)
		BIND(lua_pushnumber)
		BIND(lua_pushstring)
		BIND(lua_pushthread)
		BIND(lua_pushunsigned)
		BIND(lua_pushvalue)
		BIND(lua_pushvfstring)
		BIND(lua_rawequal)
		BIND(lua_rawget)
		BIND(lua_rawgeti)
		BIND(lua_rawgetp)
		BIND(lua_rawlen)
		BIND(lua_rawset)
		BIND(lua_rawseti)
		BIND(lua_rawsetp)
		BIND(lua_remove)
		BIND(lua_replace)
		BIND(lua_setallocf)
		BIND(lua_setfield)
		BIND(lua_setglobal)
		BIND(lua_setmetatable)
		BIND(lua_settable)
		BIND(lua_settop)
		BIND(lua_setuservalue)
		BIND(lua_status)
		BIND(lua_toboolean)
		BIND(lua_tocfunction)
		BIND(lua_tointegerx)
		BIND(lua_tolstring)
		BIND(lua_tonumberx)
		BIND(lua_topointer)
		BIND(lua_tothread)
		BIND(lua_tounsignedx)
		BIND(lua_touserdata)
		BIND(lua_type)
		BIND(lua_typename)
		BIND(lua_upvalueindex)
		BIND(lua_version)
		BIND(lua_xmove)

		BIND(lua_gethook)
		BIND(lua_gethookcount)
		BIND(lua_gethookmask)
		BIND(lua_getinfo)
		BIND(lua_getlocal)
		BIND(lua_getstack)
		BIND(lua_getupvalue)
		BIND(lua_sethook)
		BIND(lua_setlocal)
		BIND(lua_setupvalue)
		BIND(lua_upvalueid)
		BIND(lua_upvaluejoin)

		BIND(luaL_addlstring)
		BIND(luaL_addstring)
		BIND(luaL_addvalue)
		BIND(luaL_argerror)
		BIND(luaL_buffinit)
		BIND(luaL_buffinitsize)
		BIND(luaL_callmeta)
		BIND(luaL_checkany)
		BIND(luaL_checkinteger)
		BIND(luaL_checklstring)
		BIND(luaL_checknumber)
		BIND(luaL_checkoption)
		BIND(luaL_checkstack)
		BIND(luaL_checktype)
		BIND(luaL_checkudata)
		BIND(luaL_checkunsigned)
		BIND(luaL_checkversion_)
		BIND(luaL_error)
		BIND(luaL_execresult)
		BIND(luaL_fileresult)
		BIND(luaL_getmetafield)
		BIND(luaL_getsubtable)
		BIND(luaL_gsub)
		BIND(luaL_len)
		BIND(luaL_loadbufferx)
		BIND(luaL_loadfilex)
		BIND(luaL_loadstring)
		BIND(luaL_newmetatable)
		BIND(luaL_newstate)
		BIND(luaL_openlibs)
		BIND(luaL_optinteger)
		BIND(luaL_optlstring)
		BIND(luaL_optnumber)
		BIND(luaL_optunsigned)
		BIND(luaL_prepbuffsize)
		BIND(luaL_pushresult)
		BIND(luaL_pushresultsize)
		BIND(luaL_ref)
		BIND(luaL_requiref)
		BIND(luaL_setfuncs)
		BIND(luaL_setmetatable)
		BIND(luaL_testudata)
		BIND(luaL_tolstring)
		BIND(luaL_traceback)
		BIND(luaL_unref)
		BIND(luaL_where)
}

#undef BIND
